spring.application.name=spring-ai-demo
spring.ai.google.genai.api-key=AIzaSyBAnL99_oGFANXtK-BXOJgYfpx0iY4iCUQ
spring.ai.google.genai.api-version=v1
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
